from django.urls import path
from . import views # Changed import to allow views.function_name

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/<int:pk>/', views.get_employee_detail, name='employee_detail'),
    path('attendance/', views.attendance_list, name='attendance_list'),
    path('add-employee/', views.add_employee, name='add_employee'),
    path('departments/', views.department_list, name='department_list'),
    path('attendance/mark/', views.mark_attendance, name='mark_attendance'),
    path('attendance/holidays/', views.holiday_manager, name='holiday_list_create'),
    path('attendance/holidays/<int:pk>/', views.holiday_manager, name='holiday_delete'),
    path('attendance/schedule/', views.schedule_settings, name='schedule_settings'),
    path('attendance/process-daily/', views.process_daily_attendance, name='process_daily_attendance'),
    path('employees/<int:employee_id>/attendance/', views.get_employee_attendance, name='employee_attendance_history'),
    path('profile/me/', views.get_my_profile, name='get_my_profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('profile/requests/', views.list_profile_requests, name='list_profile_requests'),
    path('profile/requests/<int:pk>/handle/', views.handle_profile_request, name='handle_profile_request'),
    path('employees/<int:pk>/update/', views.admin_update_employee, name='admin_update_employee'),
    path('employees/<int:pk>/delete/', views.delete_employee, name='delete_employee'),
    path('employees/<int:pk>/reset-password/', views.reset_employee_password, name='reset_employee_password'),
    path('employees/<int:pk>/reveal-password/', views.reveal_employee_password, name='reveal_employee_password'),
    path('employees/<int:pk>/delete-resume/', views.delete_resume, name='delete_resume'),
    path('leaves/', views.manage_leaves, name='manage_leaves'),
    path('leaves/all/', views.list_all_leaves, name='list_all_leaves'),
    path('leaves/<int:pk>/handle/', views.handle_leave_request, name='handle_leave_request'),
    path('leaves/<int:pk>/mark-seen/', views.mark_leave_seen, name='mark_leave_seen'),
    path('notifications/', views.get_notifications, name='get_notifications'),
    path('notifications/history/', views.get_notification_history, name='get_notification_history'),
    path('notifications/dismiss/', views.dismiss_notification_employee, name='dismiss_notification_employee'),
    path('notifications/mark-seen/', views.mark_notification_seen, name='mark_notification_seen'),
    path('attendance/override/', views.override_attendance, name='override_attendance'),
    path('notifications/mark-all-seen/', views.mark_all_notifications_seen, name='mark_all_notifications_seen'),
    path('admin/notifications/', views.get_admin_notifications, name='get_admin_notifications'),
    path('admin/notifications/mark-all-seen/', views.mark_all_admin_notifications_seen, name='mark_all_admin_notifications_seen'),
    path('admin/notifications/dismiss/', views.dismiss_notification_admin, name='dismiss_notification_admin'),
    path('admin/verify-password/', views.verify_admin_password, name='verify_admin_password'),
    path('payroll/status/', views.get_monthly_payroll_status, name='get_monthly_payroll_status'),
    path('payroll/pay/', views.process_salary_payment, name='process_salary_payment'),
    path('payroll/pay-all/', views.pay_all_salaries, name='pay_all_salaries'),
    path('payroll/calculate/', views.calculate_payroll_deductions, name='calculate_payroll_deductions'),
    path('payroll/admin-global-history/', views.get_all_payroll_history, name='get_all_payroll_history'),
    path('payroll/history/', views.get_my_payroll_history, name='get_my_payroll_history'),
]

