# Generated by Django 6.0 on 2026-01-04 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profileupdaterequest_new_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Annual Leave', 'Annual / Paid Leave'), ('Unpaid Leave', 'Unpaid Leave'), ('Emergency Leave', 'Emergency Leave')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.employee')),
            ],
        ),
    ]
