# Generated by Django 6.0 on 2026-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_seen_by_employee',
            field=models.BooleanField(default=True),
        ),
    ]
