# Generated by Django 6.0 on 2026-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profileupdaterequest_is_seen_by_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_dismissed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='is_dismissed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
