# Generated by Django 6.0 on 2026-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_attendance_is_dismissed_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_dismissed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
