# Generated by Django 6.0 on 2026-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_dismissed_by_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_seen_by_employee',
            field=models.BooleanField(default=False),
        ),
    ]
