# Generated by Django 6.0 on 2026-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_payroll_is_dismissed_by_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
