# Generated by Django 6.0 on 2026-01-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_payroll_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='off_days',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='half_day_threshold',
            field=models.TimeField(default='15:30:00'),
        ),
    ]
