# Generated by Django 6.0 on 2026-01-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_workschedule_off_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume_2',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
