# Generated by Django 6.0 on 2026-01-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_employee_resume_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileupdaterequest',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
