# Generated by Django 6.0 on 2026-01-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_leaverequest_is_seen_by_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdaterequest',
            name='is_seen_by_employee',
            field=models.BooleanField(default=True),
        ),
    ]
