# Generated by Django 6.0 on 2026-01-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_leaverequest_is_dismissed_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
