# Generated by Django 6.0 on 2026-01-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='half_day_hours',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='check_in_tolerance',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='check_out_tolerance',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='half_day_threshold',
            field=models.TimeField(default='14:00:00'),
        ),
    ]
