# Generated by Django 6.0 on 2026-01-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_workschedule_half_day_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
