# Generated by Django 6.0 on 2026-01-13 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_leaverequest_is_seen_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
