# Generated by Django 6.0 on 2026-03-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_employee_date_of_joining'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='support@employeems.com', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('contact_address', models.TextField(default='123 Tech Park, Innovation Way, CA')),
            ],
        ),
    ]
