# Generated by Django 6.0 on 2026-03-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_companysettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
